- name: variables to print
  hosts: web
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{TOPIC}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"  
